channels:
- conda-forge
dependencies:
- python=3.10.5
- pip<=25.1.1
- pip:
  - mlflow==2.22.0
  - catboost==1.2.8
  - cloudpickle==2.2.1
  - cython==0.29.32
  - docker==7.1.0
  - google-generativeai==0.7.2
  - ipywidgets==7.7.1
  - jaraco-collections==5.1.0
  - numpy==1.26.4
  - pandas==2.2.3
  - platformdirs==4.2.2
  - scikit-learn==1.2.2
  - scipy==1.15.3
  - sqlalchemy==2.0.31
  - xgboost==3.0.2
  - zenml==0.83.0
name: mlflow-env
